### ISSUE TITLE
Using stages in CLI v2 breaks `jovo build`

### ISSUE THREAD

**Issue by rmtuckerphx** [jovotech/jovo-cli#75] opened 2018-12-22 23:37 UTC
## I'm submitting a...
- [X ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Executing `jovo build` when using `stages` and `defaultStage` should build for the default stage.

## Current Behavior
1. Create new project using `jovo new hello-jovo2`
2. `jovo build`

![image](https://user-images.githubusercontent.com/247472/50379371-b010b980-0605-11e9-972d-bdcc0856bc58.png)
3. Update `project.js` to include stages:

```js
module.exports = {
    alexaSkill: {
       nlu: 'alexa',
    },
    googleAction: {
       nlu: 'dialogflow',
    },
    defaultStage: 'local',
    stages: {
      local: {
        endpoint: `${JOVO_WEBHOOK_URL}`
      },
      dev: {
        endpoint: ""
      },
      prod: {
        endpoint: ""
      }
    }
};
```
4. Execute `jovo build` again:

![image](https://user-images.githubusercontent.com/247472/50379414-7c825f00-0606-11e9-8b36-873e7b305ec4.png)

5. Execute `jovo build --stage local`:

![image](https://user-images.githubusercontent.com/247472/50379460-8193de00-0607-11e9-95e1-043095c79e81.png)

### Error log
The error is: `The "C:\dev\voice\shazaml\hello-jovo2\project.js" file is missing or invalid!`

## Your Environment

* Jovo CLI version used: 2.0.3
* Operating System: Windows 10

**Comment by janober** [comment] 2018-12-23 10:04
Just checked and could reproduce the error. After looking into the cause I found that the issue is in the changes you made to the `project.js` file. You are using backticks instead of single/double quotes. So your code says it should look for a variable which is called "JOVO_WEBHOOK_URL" and take its value but that variable does not exist. Because of that it then errors as it can not execute the file.

So if you chang the line:
```
endpoint: `${JOVO_WEBHOOK_URL}`
```
to:
```
endpoint: '${JOVO_WEBHOOK_URL}'
```
it should work fine.

Hope that helps!

**Comment by janober** [comment] 2018-12-23 10:17
To avoid such problems in the future (as I guess that will happen quite a lot) did I just commit some code which adds "JOVO_WEBHOOK_URL" temporary as a global variable when reading the `project.js`. So with the next version of the CLI it will also work with backticks.

**Comment by jankoenig** [comment] 2018-12-23 10:47
Thanks @janober! And sorry @rmtuckerphx, that one was on me, just noticed (and updated!) that in some tutorials we used backticks for the Jovo Webhook URL. Should be changed everywhere

**Comment by jankoenig** [comment] 2019-01-03 13:58
Closing this now

**Closed by jankoenig** 2019-01-03 13:58 UTC
